/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.cartao.Cartao;
import modelo.pagamento.Tarifa;
import modelo.usuario.Usuario;
import persistencia.transpoint.PersistenciaTarifa;

/**
 *
 * @author Serenna
 */
public class HistoricoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoUsuario
     */
    private Usuario user;
    
    public HistoricoUsuario(Usuario u) {
        this.user= u;
        initComponents();
        atualizaTabela(u);
        jbcCartao.addItem("Todos");
        /*Preenche combo box de cartoes com código dos cartões*/
        for(Cartao c : u.getCartoes()){
            jbcCartao.addItem(c.getCodigo()+"");
        }
        
    }
    /*Tabela mostrando o histórico completo*/
    private void atualizaTabela(Usuario u){
        DefaultTableModel tableHist = (DefaultTableModel) jtHistorico.getModel();
        jtHistorico.setRowSorter(new TableRowSorter(tableHist));
        tableHist.getDataVector().removeAllElements();
        tableHist.fireTableDataChanged();
        PersistenciaTarifa persTarifas = new PersistenciaTarifa();
        System.out.println("att tabela historico");
        ArrayList<Tarifa> tarifas = persTarifas.geraHistoricoTarifasUsuario(u);
        if(tarifas != null){
            for (Tarifa t: tarifas){
                tableHist.addRow(new Object[] {
                    t.getData(),
                    t.getCodCartUtilizado(),
                    t.getLinha(),
                    t.getValor()

                });
            }
        }
        
    }
    /*Método para o histórico considerando os filtros*/
    private void tabelaHistorico(ArrayList<Tarifa> tarifas){
        DefaultTableModel tableHist = (DefaultTableModel) jtHistorico.getModel();
        jtHistorico.setRowSorter(new TableRowSorter(tableHist));
        tableHist.getDataVector().removeAllElements();
        tableHist.fireTableDataChanged();
        if(tarifas != null){
            for (Tarifa t: tarifas){
                tableHist.addRow(new Object[] {
                    t.getData(),
                    t.getCodCartUtilizado(),
                    t.getLinha(),
                    t.getValor()

                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtHistorico = new javax.swing.JTable();
        lbHistorico = new javax.swing.JLabel();
        lbOBS = new javax.swing.JLabel();
        jbOK = new javax.swing.JButton();
        linhaRequerida = new javax.swing.JTextField();
        lblLinha = new javax.swing.JLabel();
        lblCartao = new javax.swing.JLabel();
        jbLinha = new javax.swing.JButton();
        jbcCartao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histórico de Passagens");

        jtHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cód. Cartão", "Linha", "Valor Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtHistorico);

        lbHistorico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHistorico.setText("Seu histórico*:");

        lbOBS.setText("*Apenas mostra tarifas pagas pelo app.");

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        lblLinha.setText("Visualizar por linha:");

        lblCartao.setText("Visualizar por cartão:");

        jbLinha.setText("Ver");
        jbLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLinhaActionPerformed(evt);
            }
        });

        jbcCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcCartaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHistorico)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(linhaRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbLinha)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbcCartao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOBS, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHistorico)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCartao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linhaRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLinha)
                            .addComponent(jbcCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(lbOBS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbOKActionPerformed
/*Atualizará tabela para mostrar apenas linha selecionada ou tudo*/
    private void jbLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLinhaActionPerformed
          if(linhaRequerida.getText().isEmpty()){
            this.atualizaTabela(user);
        }else{
            PersistenciaTarifa persTarifas = new PersistenciaTarifa();
            ArrayList<Tarifa> taxes;
            int linha = Integer.parseInt(linhaRequerida.getText());
            taxes = persTarifas.historicoUsuarioLinha(user, linha);
            this.tabelaHistorico(taxes);
        }
    }//GEN-LAST:event_jbLinhaActionPerformed
/*Atualizará tabela para mostrar apenas tarifas no cartão selecionado ou tudo*/
    private void jbcCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcCartaoActionPerformed
        int ind = jbcCartao.getSelectedIndex();
        if(ind!=0){
            int cod = Integer.parseInt(jbcCartao.getSelectedItem()+"");
            PersistenciaTarifa persTarifas = new PersistenciaTarifa();
            ArrayList<Tarifa> taxes;
            taxes = persTarifas.historicoUsuarioCartao(cod);
            this.tabelaHistorico(taxes);
        }else{
            this.atualizaTabela(user);
        }
    }//GEN-LAST:event_jbcCartaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*Um usuário teste pra IDE não reclamar, não se deve executar esta tela sozinha*/
        Usuario exibU = new Usuario();
        exibU.setNome("Test User");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoUsuario(exibU).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLinha;
    private javax.swing.JButton jbOK;
    private javax.swing.JComboBox<String> jbcCartao;
    private javax.swing.JTable jtHistorico;
    private javax.swing.JLabel lbHistorico;
    private javax.swing.JLabel lbOBS;
    private javax.swing.JLabel lblCartao;
    private javax.swing.JLabel lblLinha;
    private javax.swing.JTextField linhaRequerida;
    // End of variables declaration//GEN-END:variables
}
