/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.cartao.Cartao;
import modelo.pagamento.Recarga;
import modelo.usuario.Usuario;
import persistencia.transpoint.PersistenciaCartao;
import persistencia.transpoint.PersistenciaUsuario;

/**
 *
 * @author Serenna
 */
public class UIRecarga extends javax.swing.JFrame {

    /**
     * Creates new form UIRecarga
     */
    private Cartao card;

    public Cartao getCard() {
        return card;
    }

    public void setCard(Cartao card) {
        this.card = card;
    }
        
    
    public UIRecarga(int codCard) {
        PersistenciaCartao persC = new PersistenciaCartao();
        this.card = persC.recuperaCartao(codCard);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        opBoleto = new javax.swing.JRadioButton();
        opCartaoCredito = new javax.swing.JRadioButton();
        lbMetodoPag = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        valorRecarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));

        buttonGroup1.add(opBoleto);
        opBoleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBoleto.setText("Boleto");

        buttonGroup1.add(opCartaoCredito);
        opCartaoCredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opCartaoCredito.setText("Cartão de Crédito");

        lbMetodoPag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMetodoPag.setText("Selecione o método de pagamento");

        lbValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbValor.setText("Valor:");

        confirmButton.setText("OK");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opBoleto)
                            .addComponent(lbMetodoPag)
                            .addComponent(opCartaoCredito)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMetodoPag)
                .addGap(18, 18, 18)
                .addComponent(opBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opCartaoCredito)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        Recarga nRecarga;
        PersistenciaCartao persCard = new PersistenciaCartao();
        PersistenciaUsuario persUser = new PersistenciaUsuario();
        Usuario bfUser = persUser.recuperaUsuario(card.getCpfUser()); //usuário "anterior"
        try {
            nRecarga = new Recarga(this.card,Double.parseDouble(valorRecarga.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
       
        if(opBoleto.isSelected()){
            nRecarga.setFormaPagamento("Boleto");
        } else if (opCartaoCredito.isSelected()) {
            nRecarga.setFormaPagamento("Cartão de Crédito");
        }
        persCard.atualizaCartao(card);
        this.dispose();
        UITranspoint mainTela = new UITranspoint(bfUser); //reabrimos esta tela para o saldo atualizar na tabela
        mainTela.setVisible(true);
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        PersistenciaUsuario persUser = new PersistenciaUsuario();
        Usuario bfUser = persUser.recuperaUsuario(card.getCpfUser()); //usuário "anterior"
        UITranspoint mainTela = new UITranspoint(bfUser); //reabre
        mainTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        int testeCod = 12345;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIRecarga(testeCod).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel lbMetodoPag;
    private javax.swing.JLabel lbValor;
    private javax.swing.JRadioButton opBoleto;
    private javax.swing.JRadioButton opCartaoCredito;
    private javax.swing.JTextField valorRecarga;
    // End of variables declaration//GEN-END:variables
}
